### PR TITLE
Add example/testing Docker Compose manifests

### PR DESCRIPTION
**Pull request by pataquets**
For both Redis and Memcached stacks.
Using Docker Hub's public images by default.
With commented out sample lines for building local code and for customizing Redis/Memcached command line parameters.

### CODE REVIEW

**Comment by pataquets** [comment]
@itamarhaber ping?

**Comment by itamarhaber** [comment]
Hello @pataquets 

Thanks for the PR - the yamls look ok. Can you explain why they should be a part of the project?

**Comment by pataquets** [comment]
They serve both as Docker usage quick examples and as a basis to allow local develop/build/run workflow based on Docker, too (no dev libs/tools needed to install).

**Comment by itamarhaber** [comment]
Thanks, I had figured out that much, but I'm still not convinced that they should be added. @RoeyPrat @YaacovHazan what do you say?

**Comment by RoeyPrat** [comment]
I think examples should be added in markdown files, in code snippets.

As for testing, we should probably add continuous integration using circle-ci or github actions

**Comment by pataquets** [comment]
Examples in markdown would be another way of doing it, although I prefer the manifest because it's runnable straight away and this the code are the docs, but just a matter of personal preferences, I suppose.
However, for the local dev workflow, it takes away all the complexities not by just setting up and installing all the build deps, but also taking care of installing and running whatever Redis/Memcached service is also necessary with ready and obvious command line tuning. You don't have to download and install them and you even can use any version, independent of you host OS packaged ones. Not everyone knows/wants to install a daemon just for development, so a manifest leaves your system tidy after you're finished without leaving traces.
As for the docs you mention, I can add an example run command in the readme, if it helps.

**Comment by pataquets** [comment]
@itamarhaber @RoeyPrat any feedback on this?

**Comment by pataquets** [comment]
@itamarhaber @RoeyPrat checking the Dockerfile, I've realized that the build is done using source code _downloaded_ from Github. Most of the Docker workflow advantages come from building the artifact from local Docker build context, especialy the source code.
I've changed this, so now it makes more sense to have a Docker Compose manifest for local development, since it will build from local source, too. Thus, anybody can start hacking right away without having to install anything else besides Docker and Docker Compose. Now it makes more sense, IMO.

**Comment by pataquets** [comment]
@RoeyPrat : Done. Now that #113 is in, makes more sense to build images by using local context instead of pulling them.

**Comment by RoeyPrat** [comment]
@itamarhaber my +1 doesn't allow merging :)

**Comment by RoeyPrat** [comment]
thanks @pataquets!

**Pull request merged**
